if (typeof __googlefc.fcKernelManager.run === 'function') {"use strict";this.default_ContributorServingResponseClientJs=this.default_ContributorServingResponseClientJs||{};(function(_){var window=this;
try{
var ap=function(a){this.A=_.r(a)};_.t(ap,_.I);var bp=function(a){this.D=a;this.l=this.j=!1};bp.prototype.getConsentStatus=function(){if(!this.j){var a=this.D,b=a.L,c=new _.rg,d=new _.ho;var e=new ap;e=_.fo(e,1,!0);d=_.C(d,4,e);b.call(a,_.io(c,d));this.j=!0}return 0};bp.prototype.getConsentedProviderIds=function(){if(!this.l){var a=this.D,b=a.L,c=new _.rg,d=new _.ho;var e=new ap;e=_.fo(e,2,!0);d=_.C(d,4,e);b.call(a,_.io(c,d));this.l=!0}return[]};
var cp=function(a){var b=new bp(a.D);_.eo("getConsentStatus",function(){return b.getConsentStatus()});_.eo("getConsentedProviderIds",function(){return b.getConsentedProviderIds()});_.No(a.D,"consentData","legacyNoData")},dp=function(a){this.A=_.r(a)};_.t(dp,_.I);var ep=function(a){this.A=_.r(a)};_.t(ep,_.I);ep.prototype.getWhitelistStatus=function(){return _.F(this,2)};var fp=function(a){this.A=_.r(a)};_.t(fp,_.I);
var gp=_.ed(fp),hp=function(a,b,c){this.o=a;this.j=_.z(b,dp,1);this.F=_.z(b,_.Jk,3);this.C=_.z(b,ep,4);a=this.o.location.hostname;this.G=_.Lg(this.j,2)&&_.N(this.j,2)!==""?_.N(this.j,2):a;a=new _.Ug(_.Kk(this.F));this.B=new _.eh(_.q.document,this.G,a);this.console=null;this.l=new _.Zo(this.o,c,a)};
hp.prototype.run=function(){if(_.N(this.j,3)){var a=this.B,b=_.N(this.j,3),c=_.gh(a),d=new _.Xg;b=_.kg(d,1,b);c=_.C(c,1,b);_.kh(a,c)}else _.hh(this.B,"FCNEC");cp(this.l);_.$o(this.l,_.F(this.C,1),this.C.getWhitelistStatus());var e;a=(e=this.o.googlefc)==null?void 0:e.__executeManualDeployment;a!==void 0&&typeof a==="function"&&_.No(this.l.D,"manualDeploymentApi")};var ip=function(){};ip.prototype.run=function(a,b,c){var d;return _.u(function(e){d=gp(b);(new hp(a,d,c)).run();return e.return({})})};_.Ok(7,new ip);
}catch(e){_._DumpException(e)}
}).call(this,this.default_ContributorServingResponseClientJs);
// Google Inc.

//# sourceURL=/_/mss/boq-content-ads-contributor/_/js/k=boq-content-ads-contributor.ContributorServingResponseClientJs.en_GB.0zH8UJEUXco.es5.O/d=1/exm=ad_blocking_detection_executable,kernel_loader,loader_js_executable,web_iab_tcf_v2_signal_executable/ed=1/rs=AJlcJMz_zjdzWw7J_X0T3uF7KxMHpC3KsA/m=cookie_refresh_executable
__googlefc.fcKernelManager.run('\x5b\x5b\x5b7,\x22\x5b\x5bnull,\\\x22mycsg.in\\\x22,\\\x22AKsRol93sYBOE7J_OqpQOfXlg3WhdvjtEQh2hv-vDGAJqDNYRjkBDXwZSv7geNRwyV9i9iykExyOsQFfQj15u5piSJqc7yz7vVv6X4GwB5t_w17b7w1_MzbTr44TrVeIAy2wISliiJVw6CUXNPBIIPPAZkSoYf3ZWw\\\\u003d\\\\u003d\\\x22\x5d,null,\x5bnull,null,null,\x5bnull,null,null,\\\x22https:\/\/fundingchoicesmessages.google.com\/el\/AGSKWxV0lOQFAGAGQ7ojKuj_C9G-S8BFFrIwUSy9Jw4eBdeY_9M6wug5iifwV03c0EksZxrb-IsMkxYeQlYf2QQe-Ibv38iVo97ggnf4hPH2_c_p6YCp5QoWKfPCC4mE4w5uF3qgGVSI9A\\\\u003d\\\\u003d\\\x22\x5d,null,\x5bnull,\x5b7,9,6\x5d,null,2,null,\\\x22en\\\x22,null,null,null,null,null,1\x5d\x5d,\x5b3,1\x5d\x5d\x22\x5d\x5d,\x5bnull,null,null,\x22https:\/\/fundingchoicesmessages.google.com\/f\/AGSKWxVQ62BcWsAJ_zwAnX-z0hK-L_UwbKrtCoyQclXN_-MsmfFr40p-3zKKyWQhWG6OIU4ObAf7FiECoxpmymT8H_al_pSY-cDNzwc-q6ixHYt97zx4F80-KafJ8yr0c9QwXmBoPIcjuA\\u003d\\u003d\x22\x5d\x5d');}