if (typeof __googlefc.fcKernelManager.run === 'function') {"use strict";this.default_ContributorServingResponseClientJs=this.default_ContributorServingResponseClientJs||{};(function(_){var window=this;
try{
var ap=function(a){this.A=_.r(a)};_.t(ap,_.I);var bp=function(a){this.D=a;this.l=this.j=!1};bp.prototype.getConsentStatus=function(){if(!this.j){var a=this.D,b=a.L,c=new _.sg,d=new _.ho;var e=new ap;e=_.fo(e,1,!0);d=_.C(d,4,e);b.call(a,_.io(c,d));this.j=!0}return 0};bp.prototype.getConsentedProviderIds=function(){if(!this.l){var a=this.D,b=a.L,c=new _.sg,d=new _.ho;var e=new ap;e=_.fo(e,2,!0);d=_.C(d,4,e);b.call(a,_.io(c,d));this.l=!0}return[]};
var cp=function(a){var b=new bp(a.D);_.eo("getConsentStatus",function(){return b.getConsentStatus()});_.eo("getConsentedProviderIds",function(){return b.getConsentedProviderIds()});_.No(a.D,"consentData","legacyNoData")},dp=function(a){this.A=_.r(a)};_.t(dp,_.I);var ep=function(a){this.A=_.r(a)};_.t(ep,_.I);ep.prototype.getWhitelistStatus=function(){return _.F(this,2)};var fp=function(a){this.A=_.r(a)};_.t(fp,_.I);
var gp=_.ed(fp),hp=function(a,b,c){this.o=a;this.j=_.z(b,dp,1);this.F=_.z(b,_.Jk,3);this.C=_.z(b,ep,4);a=this.o.location.hostname;this.G=_.Mg(this.j,2)&&_.N(this.j,2)!==""?_.N(this.j,2):a;a=new _.Vg(_.Kk(this.F));this.B=new _.eh(_.q.document,this.G,a);this.console=null;this.l=new _.Zo(this.o,c,a)};
hp.prototype.run=function(){if(_.N(this.j,3)){var a=this.B,b=_.N(this.j,3),c=_.gh(a),d=new _.Yg;b=_.ng(d,1,b);c=_.C(c,1,b);_.kh(a,c)}else _.hh(this.B,"FCNEC");cp(this.l);_.$o(this.l,_.F(this.C,1),this.C.getWhitelistStatus());var e;a=(e=this.o.googlefc)==null?void 0:e.__executeManualDeployment;a!==void 0&&typeof a==="function"&&_.No(this.l.D,"manualDeploymentApi")};var ip=function(){};ip.prototype.run=function(a,b,c){var d;return _.u(function(e){d=gp(b);(new hp(a,d,c)).run();return e.return({})})};_.Ok(7,new ip);
}catch(e){_._DumpException(e)}
}).call(this,this.default_ContributorServingResponseClientJs);
// Google Inc.

//# sourceURL=/_/mss/boq-content-ads-contributor/_/js/k=boq-content-ads-contributor.ContributorServingResponseClientJs.en_GB.l7RAI9OiEn4.es5.O/d=1/exm=ad_blocking_detection_executable,kernel_loader,loader_js_executable,web_iab_tcf_v2_signal_executable/ed=1/rs=AJlcJMyoIv6eh76Ljc6BL1z_YYt8bfgQoQ/m=cookie_refresh_executable
__googlefc.fcKernelManager.run('\x5b\x5b\x5b7,\x22\x5b\x5bnull,\\\x22mycsg.in\\\x22,\\\x22AKsRol9YaEt8Mkck71004bBkNmjUnCLO8xTDsRiyWI5E0K807Q0OoEMq7KY6YOn5aLmFl-v3WhjtXxHeJuyAyl7GQvtRsy-Xx1e1MfXLChIM30RW29x1bk1-hnepf3rr3tXd-7yZKdmeyEHTuPEeb0ya1_h3OCh5_Q\\\\u003d\\\\u003d\\\x22\x5d,null,\x5bnull,null,null,\x5bnull,null,null,\\\x22https:\/\/fundingchoicesmessages.google.com\/el\/AGSKWxU3MLSsuEwdEFa8bm5ZchMYgly7lKel_AhEq8tKBCM1XbYM4hveFc9wPuqiwvZvvLuxvZRh3KdfFA98DdWipfENb2au-sIZcYXeB97UubVxKy6EiI4GA0pGtdZI8A9o0pTDMSyBqA\\\\u003d\\\\u003d\\\x22\x5d,null,\x5bnull,\x5b7,9,6\x5d,null,2,null,\\\x22en\\\x22,null,null,null,null,null,1\x5d\x5d,\x5b3,1\x5d\x5d\x22\x5d\x5d,\x5bnull,null,null,\x22https:\/\/fundingchoicesmessages.google.com\/f\/AGSKWxVN_WNS3vnbWvE5WRTECqjVoL2KzpjBNhRdmfdbmZR8KTKf336ZsnyuDSjXTQp95WkYPB-qdCRVVrGRwVXJ5vUjbx8URIs7yR4-cqLkby0bpYfta7lVaBk7lckSuogCVCTAdv8_IA\\u003d\\u003d\x22\x5d\x5d');}